site_name: OnBlick Automation Reference Guide
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      locale: en
  - git-authors
      
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  analytics:
    provider: google
    property: G-KHXS6BPD46
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: -1
          note: >- 
            Thanks for your feedback! Help us improve this page by
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSeWYeNOUVBIXC6z-oSacs6OQd4wVFryX6tZ69UhSDteAFN6fw/viewform" target="_blank" rel="noopener">telling us what you're missing</a>.
      
theme:
  name: material
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: cyan
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: assets/images/onblick-logo.gif

extra_css:
  - assets/styles/extras.css

extra_javascript:
  - assets/scripts/extras.js

nav:
  - Home: index.md
  - Getting Started:
      - Conventions: getting-started/conventions.md
      - Prerequisites: getting-started/prerequisites.md
      - Project Structure: getting-started/project-structure.md
      - Setting Up the Environment: getting-started/setting-up.md
      - Building the solution: getting-started/build.md
  - Writing Tests:
      - Writing Proper Test Cases: writing-tests/test-cases.md
      - Writing Your First Test: writing-tests/first-test.md
      - Running Tests: writing-tests/running-tests.md
      - Module-wise Tests Covered: 
        - Onboard Tests: writing-tests/module-wise/onboard-tests.md
        - Change Password Tests: writing-tests/module-wise/change-password-tests.md
        - End Employment Tests: writing-tests/module-wise/end-employment-tests.md
        - Timesheet Tests: writing-tests/module-wise/timesheet-tests.md
        - Form I-983 Tests: writing-tests/module-wise/form-i983-tests.md
        - Sign Request Tests: writing-tests/module-wise/sign-request-tests.md
        - Project Tests: writing-tests/module-wise/project-tests.md
        - W4 Tests: writing-tests/module-wise/w4-tests.md
        - I9 Tests: writing-tests/module-wise/i9-tests.md
        - H1B Tests: 
          - Upload H-1B Tests: writing-tests/module-wise/upload-h1b-tests.md
          - Initiate H-1B Tests: writing-tests/module-wise/initiate-h1b-tests.md
  - Utilities and Helpers:
      - Pre-defined Utilities:
          - Attribute Extensions: utilities-and-helpers/pre-defined-utilities/attribute-extensions.md
          - Browser Options: utilities-and-helpers/pre-defined-utilities/browser-options.md
          - Extent Manager: utilities-and-helpers/pre-defined-utilities/extent-manager.md
          - Login Creds: utilities-and-helpers/pre-defined-utilities/login-creds.md
          - Reports Generation Class: utilities-and-helpers/pre-defined-utilities/reports-generation-class.md
          - Shared Failure Context: utilities-and-helpers/pre-defined-utilities/shared-failure-context.md
          - Soft Assertion: utilities-and-helpers/pre-defined-utilities/soft-assertion.md
          - Test Execution Helper: utilities-and-helpers/pre-defined-utilities/testexecution-helper.md
          - URLs: utilities-and-helpers/pre-defined-utilities/urls.md
          - Wait Helpers: utilities-and-helpers/pre-defined-utilities/wait-helpers.md
      - Web Extensions:
          - WebDriverExtensions: utilities-and-helpers/webextensions/webdriver-extensions.md
          - WebElementExtensions: utilities-and-helpers/webextensions/webelement-extensions.md
  - Page Object Model (POM):
      - Introduction: page-object-model/pom-introduction.md
      - Guidelines: page-object-model/pom-guidelines.md
      - Frequently Utilized POM Classes:
          - LoginPage: page-object-model/frequently-utilized-pom-classes/login-page.md
          - OnboardPage: page-object-model/frequently-utilized-pom-classes/onboard-page.md
          - SettingsPage: page-object-model/frequently-utilized-pom-classes/settings-page.md
          - WorkforcePage: page-object-model/frequently-utilized-pom-classes/workforce-page.md
      - Mail Pages:
          - MailhogPage: page-object-model/frequently-utilized-pom-classes/mail-pages/mailhog-page.md
          - MailinatorPage: page-object-model/frequently-utilized-pom-classes/mail-pages/mailinator-page.md
          - MaildropPage: page-object-model/frequently-utilized-pom-classes/mail-pages/maildrop-page.md
  - Debugging and Troubleshooting:
      - Debugging: debugging-and-troubleshooting/debugging.md
      - Troubleshooting: debugging-and-troubleshooting/troubleshooting.md
  - Advanced Topics:
      - Working with System Files: advanced-topics/system-files.md
      - Reports: advanced-topics/reports.md
      - Continuous Integration: advanced-topics/ci.md
  - Best Practices and Tools:
      - Best Practices: best-practices-and-tools/best-practices.md
      - Using Git: best-practices-and-tools/git.md
      - Must know Shortcuts: best-practices-and-tools/vs-shortcuts.md
